mfd, tps65910: Fix build breakage caused by tps65910 gpio directory move
drivers/gpio/tps65910-gpio.c:96: error: implicit declaration of function 'gpiochip_add'

looks this was broken by moving the tps65910 gpio directory move.

Signed-off-by: Liam Girdwood <lrg@ti.com>
Cc: Samuel Ortiz <sameo@linux.intel.com>
Cc: Jorge Eduardo Candelaria <jedu@slimlogic.co.uk>
Cc: Mark Brown <broonie@opensource.wolfsonmicro.com>
Cc: Randy Dunlap <randy.dunlap@oracle.com>
Link: http://lkml.kernel.org/r/1306530788.3366.30.camel@odin
Signed-off-by: Ingo Molnar <mingo@elte.hu>